// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://logyrzpipxjckseqlsgv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvZ3lyenBpcHhqY2tzZXFsc2d2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NDUwNjgsImV4cCI6MjA3MTQyMTA2OH0.zKYEi1MvUwMNek0qL9D--sWGAZT11gklfMSEPe2hd3s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});